In [407]:
import pandas as pd
import os

In [408]:
energyC = pd.read_csv (r'INT-Export-worldEnergyYearly.csv')

In [409]:
energyC

,Report generated on: 12-29-2022 11:25:43,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43
0,API,NaN,1980,1981,1982,1983,1984,1985,1986,1987,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
1,NaN,total energy production (quad Btu),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,INTL.44-1-WORL-QBTU.A,World,296.3424356,291.2937659,290.128203,293.047718,308.9468834,316.4925296,326.77104,334.398773,...,545.5966162,553.7450243,563.207886,568.3123474,564.492523,579.0744861,600.6668826,611.1215834,586.0864248,606.8165994
3,INTL.44-1-AFG-QBTU.A,Afghanistan,0.072561156,0.092723655,0.095067867,0.09971282,0.099827343,0.12096783,0.120549769,0.114835081,...,0.037492263,0.040816563,0.044789507,0.042057997,0.049505118,0.059500543,0.063175856,0.05530024,0.010260242,0.041213085
4,INTL.44-1-ALB-QBTU.A,Albania,0.15556162,0.158691383,0.205944156,0.234693222,0.191025062,0.191729938,0.196595523,0.202388064,...,0.084037874,0.105636486,0.092961941,0.102254704,0.125356216,0.08259616,0.116337106,0.091399758,0.089594086,0.119993451
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1620,INTL.4418-1-WAK-QBTU.A,Wake Island,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1621,INTL.4418-1-ESH-QBTU.A,Western Sahara,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1622,INTL.4418-1-YEM-QBTU.A,Yemen,0,0,0,0,0,0,0,0,...,0.000028548,0.000047705,0.0000951,0.001081004,0.00143096,0.001787322,0.004406336,0.00431002,0.00429877,0.005244499
1623,INTL.4418-1-ZMB-QBTU.A,Zambia,0.09359591,0.101143253,0.103630548,0.104463781,0.10213452,0.102923844,0.10127397,0.087029907,...,0.116989704,0.126075766,0.132884219,0.120961589,0.101470417,0.115780904,0.125502418,0.111562837,0.114233794,0.142991022
1624,INTL.4418-1-ZWE-QBTU.A,Zimbabwe,0.041981256,0.043344924,0.038080186,0.039651764,0.036508115,0.032800352,0.033392709,0.026619417,...,0.052395096,0.048852293,0.053437276,0.048243558,0.029787245,0.039124475,0.048907831,0.040075727,0.034551118,0.036331353

In [410]:
energyC.columns = energyC.iloc[0]

In [411]:
energyC = energyC.drop(['API'], axis=1)
#The API info is not needed

In [412]:
energyC.rename(columns={ energyC.columns[0]: 'World'}, inplace = True)

In [413]:
energyC

,World,1980,1981,1982,1983,1984,1985,1986,1987,1988,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,NaN,1980,1981,1982,1983,1984,1985,1986,1987,1988,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
1,total energy production (quad Btu),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,World,296.3424356,291.2937659,290.128203,293.047718,308.9468834,316.4925296,326.77104,334.398773,347.4260513,...,545.5966162,553.7450243,563.207886,568.3123474,564.492523,579.0744861,600.6668826,611.1215834,586.0864248,606.8165994
3,Afghanistan,0.072561156,0.092723655,0.095067867,0.09971282,0.099827343,0.12096783,0.120549769,0.114835081,0.121394396,...,0.037492263,0.040816563,0.044789507,0.042057997,0.049505118,0.059500543,0.063175856,0.05530024,0.010260242,0.041213085
4,Albania,0.15556162,0.158691383,0.205944156,0.234693222,0.191025062,0.191729938,0.196595523,0.202388064,0.186417418,...,0.084037874,0.105636486,0.092961941,0.102254704,0.125356216,0.08259616,0.116337106,0.091399758,0.089594086,0.119993451
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1620,Wake Island,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1621,Western Sahara,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1622,Yemen,0,0,0,0,0,0,0,0,0,...,0.000028548,0.000047705,0.0000951,0.001081004,0.00143096,0.001787322,0.004406336,0.00431002,0.00429877,0.005244499
1623,Zambia,0.09359591,0.101143253,0.103630548,0.104463781,0.10213452,0.102923844,0.10127397,0.087029907,0.085596284,...,0.116989704,0.126075766,0.132884219,0.120961589,0.101470417,0.115780904,0.125502418,0.111562837,0.114233794,0.142991022
1624,Zimbabwe,0.041981256,0.043344924,0.038080186,0.039651764,0.036508115,0.032800352,0.033392709,0.026619417,0.028233951,...,0.052395096,0.048852293,0.053437276,0.048243558,0.029787245,0.039124475,0.048907831,0.040075727,0.034551118,0.036331353

In [414]:
energyC = energyC.iloc[2] #We only need the world info for the analysis

In [415]:
energyC #Dataset #1

0
World          World
1980     296.3424356
1981     291.2937659
1982      290.128203
1983      293.047718
1984     308.9468834
1985     316.4925296
1986       326.77104
1987      334.398773
1988     347.4260513
1989     354.0364853
1990     357.6579078
1991     354.9531364
1992     353.7276721
1993     354.3861018
1994     360.4427565
1995     368.3400726
1996     377.5186505
1997     382.0654227
1998     386.5962198
1999        386.3867
2000     399.5432742
2001     405.2191265
2002     407.0617188
2003     422.7334243
2004     445.0398125
2005     460.9817015
2006     473.3646374
2007     481.9619898
2008     495.3029326
2009      492.727998
2010     517.8563437
2011     533.3323144
2012     545.5966162
2013     553.7450243
2014      563.207886
2015     568.3123474
2016      564.492523
2017     579.0744861
2018     600.6668826
2019     611.1215834
2020     586.0864248
2021     606.8165994
Name: 2, dtype: object

In [416]:
gdpC = pd.read_csv (r'GDP WorldWide Resaved.csv')

In [417]:
gdpC.head(25)

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Last Updated Date,12/22/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Country Name,Country Code,Indicator Name,Indicator Code,1.960000e+03,1.961000e+03,1.962000e+03,1.963000e+03,1.964000e+03,1.965000e+03,...,2.012000e+03,2.013000e+03,2.014000e+03,2.015000e+03,2.016000e+03,2.017000e+03,2.018000e+03,2.019000e+03,2.020000e+03,2.021000e+03
4,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.615084e+09,2.727933e+09,2.791061e+09,2.963128e+09,2.983799e+09,3.092179e+09,3.202235e+09,3.368970e+09,2.610039e+09,3.126019e+09
5,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,2.129081e+10,2.180870e+10,2.370727e+10,2.821034e+10,2.611906e+10,2.968249e+10,...,9.725730e+11,9.834730e+11,1.003770e+12,9.245230e+11,8.827210e+11,1.021120e+12,1.007240e+12,1.001020e+12,9.274840e+11,1.080710e+12
6,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,...,2.020357e+10,2.056449e+10,2.055058e+10,1.999816e+10,1.801956e+10,1.889635e+10,1.841885e+10,1.890449e+10,2.014344e+10,1.478686e+10
7,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,1.040414e+10,1.112789e+10,1.194319e+10,1.267633e+10,1.383837e+10,1.486223e+10,...,7.360400e+11,8.322170e+11,8.924980e+11,7.669580e+11,6.905450e+11,6.837480e+11,7.663600e+11,7.947190e+11,7.848000e+11,8.401870e+11
8,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.249980e+11,1.334020e+11,1.372440e+11,8.721930e+10,4.984049e+10,6.897277e+10,7.779294e+10,6.930911e+10,5.361907e+10,6.740429e+10
9,Albania,ALB,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.231983e+10,1.277622e+10,1.322815e+10,1.138685e+10,1.186120e+10,1.301969e+10,1.515643e+10,1.540183e+10,1.513187e+10,1.825579e+10
10,Andorra,AND,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.188809e+09,3.193704e+09,3.271808e+09,2.789870e+09,2.896679e+09,3.000181e+09,3.218316e+09,3.155065e+09,2.891022e+09,3.330282e+09
11,Arab World,ARB,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.787170e+12,2.843530e+12,2.895460e+12,2.538930e+12,2.516490e+12,2.598090e+12,2.800430e+12,2.818500e+12,2.490810e+12,2.860720e+12
12,United Arab Emirates,ARE,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.846100e+11,4.002190e+11,4.141050e+11,3.702750e+11,3.692550e+11,3.905170e+11,4.270490e+11,4.179900e+11,3.494730e+11,4.150220e+11
13,Argentina,ARG,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,2.445060e+10,1.827212e+10,2.560525e+10,2.834471e+10,...,5.459820e+11,5.520250e+11,5.263200e+11,5.947490e+11,5.575310e+11,6.436290e+11,5.248200e+11,4.477550e+11,3.855400e+11,4.872270e+11
14,Armenia,ARM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.061932e+10,1.112147e+10,1.160951e+10,1.055334e+10,1.054614e+10,1.152746e+10,1.245794e+10,1.361929e+10,1.264170e+10,1.386141e+10
15,American Samoa,ASM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,6.400000e+08,6.380000e+08,6.430000e+08,6.730000e+08,6.710000e+08,6.120000e+08,6.390000e+08,6.470000e+08,7.160000e+08,7.090000e+08
16,Antigua and Barbuda,ATG,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.199948e+09,1.181448e+09,1.249733e+09,1.336693e+09,1.436585e+09,1.467978e+09,1.605944e+09,1.687533e+09,1.370281e+09,1.471126e+09
17,Australia,AUS,GDP (current US$),NY.GDP.MKTP.CD,1.860567e+10,1.968194e+10,1.992160e+10,2.153881e+10,2.379998e+10,2.597491e+10,...,1.546890e+12,1.576380e+12,1.467550e+12,1.350620e+12,1.206540e+12,1.326520e+12,1.428290e+12,1.392230e+12,1.326900e+12,1.552670e+12
18,Austria,AUT,GDP (current US$),NY.GDP.MKTP.CD,6.592694e+09,7.311750e+09,7.756110e+09,8.374175e+09,9.169984e+09,9.994071e+09,...,4.094020e+11,4.301910e+11,4.425850e+11,3.819710e+11,3.958370e+11,4.172610e+11,4.549910e+11,4.446210e+11,4.352250e+11,4.803680e+11
19,Azerbaijan,AZE,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,6.968394e+10,7.416444e+10,7.524429e+10,5.307437e+10,3.786752e+10,4.086556e+10,4.711294e+10,4.817424e+10,4.269300e+10,5.462218e+10
20,Burundi,BDI,GDP (current US$),NY.GDP.MKTP.CD,1.960000e+08,2.030000e+08,2.135000e+08,2.327500e+08,2.607500e+08,1.589950e+08,...,2.333341e+09,2.451607e+09,2.705783e+09,3.104004e+09,2.639321e+09,2.712324e+09,2.660124e+09,2.576519e+09,2.649672e+09,2.779813e+09
21,Belgium,BEL,GDP (current US$),NY.GDP.MKTP.CD,1.165872e+10,1.240015e+10,1.326402e+10,1.426002e+10,1.596011e+10,1.737146e+10,...,4.961530e+11,5.217910e+11,5.353900e+11,4.623360e+11,4.760630e+11,5.027650e+11,5.432990e+11,5.358310e+11,5.252120e+11,5.941040e+11
22,Benin,BEN,GDP (current US$),NY.GDP.MKTP.CD,2.261956e+08,2.356682e+08,2.364349e+08,2.539276e+08,2.698190e+08,2.899087e+08,...,1.114136e+10,1.251785e+10,1.328453e+10,1.138816e+10,1.182107e+10,1.270166e+10,1.426241e+10,1.439169e+10,1.565155e+10,1.714492e+10
23,Burkina Faso,BFA,GDP (current US$),NY.GDP.MKTP.CD,3.304428e+08,3.502472e+08,3.795670e+08,3.940406e+08,4.103216e+08,4.229168e+08,...,1.256102e+10,1.344430e+10,1.394302e+10,1.183216e+10,1.283336e+10,1.410696e+10,1.589007e+10,1.617816e+10,1.793361e+10,1.973762e+10
24,Bangladesh,BGD,GDP (current US$),NY.GDP.MKTP.CD,4.274894e+09,4.817580e+09,5.081413e+09,5.319458e+09,5.386055e+09,5.906637e+09,...,1.333560e+11,1.499900e+11,1.728850e+11,1.950790e+11,2.652360e+11,2.937550e+11,3.213790e+11,3.512380e+11,3.739020e+11,4.162650e+11

In [418]:
gdpC.columns = gdpC.iloc[3].astype(str) #as a string so it can be used with loc function

In [419]:
gdpC.tail(25) #World is index 263

3,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0
245,Sub-Saharan Africa (IDA & IBRD countries),TSS,GDP (current US$),NY.GDP.MKTP.CD,3.116738e+10,3.242300e+10,3.508183e+10,4.010602e+10,3.937704e+10,4.382660e+10,...,1.708390e+12,1.815690e+12,1.896270e+12,1.691480e+12,1.573270e+12,1.704870e+12,1.773600e+12,1.795740e+12,1.712280e+12,1.920900e+12
246,Trinidad and Tobago,TTO,GDP (current US$),NY.GDP.MKTP.CD,5.356701e+08,5.849612e+08,6.193192e+08,6.782354e+08,7.118934e+08,7.365689e+08,...,2.712171e+10,2.855745e+10,2.948901e+10,2.685197e+10,2.349622e+10,2.379769e+10,2.432236e+10,2.384956e+10,2.105943e+10,2.446020e+10
247,Tunisia,TUN,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,9.910476e+08,...,4.731116e+10,4.868419e+10,5.027107e+10,4.578008e+10,4.436075e+10,4.216397e+10,4.268597e+10,4.190611e+10,4.253783e+10,4.668674e+10
248,Turkiye,TUR,GDP (current US$),NY.GDP.MKTP.CD,1.398357e+10,7.988889e+09,8.922222e+09,1.035556e+10,1.117778e+10,1.196667e+10,...,8.805560e+11,9.577830e+11,9.389530e+11,8.643170e+11,8.696930e+11,8.589960e+11,7.784720e+11,7.599370e+11,7.202890e+11,8.190350e+11
249,Tuvalu,TUV,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.934562e+07,3.861749e+07,3.875969e+07,3.681166e+07,4.162950e+07,4.521766e+07,4.781829e+07,5.422315e+07,5.505471e+07,6.310096e+07
250,Tanzania,TZA,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.965052e+10,4.568053e+10,4.996483e+10,4.737860e+10,4.977400e+10,5.332065e+10,5.700369e+10,6.113687e+10,6.240971e+10,6.784105e+10
251,Uganda,UGA,GDP (current US$),NY.GDP.MKTP.CD,4.230084e+08,4.415241e+08,4.490126e+08,5.161478e+08,5.890566e+08,8.848739e+08,...,2.730592e+10,2.891579e+10,3.261240e+10,3.238718e+10,2.920399e+10,3.074447e+10,3.292703e+10,3.535306e+10,3.760037e+10,4.052979e+10
252,Ukraine,UKR,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.825920e+11,1.904990e+11,1.335030e+11,9.103096e+10,9.335599e+10,1.120910e+11,1.308910e+11,1.538830e+11,1.566180e+11,2.000860e+11
253,Upper middle income,UMC,GDP (current US$),NY.GDP.MKTP.CD,2.419480e+11,2.183620e+11,2.239610e+11,2.349680e+11,2.696460e+11,3.012360e+11,...,1.891480e+13,2.030660e+13,2.093960e+13,1.966350e+13,1.954980e+13,2.164480e+13,2.330450e+13,2.368170e+13,2.285140e+13,2.710410e+13
254,Uruguay,URY,GDP (current US$),NY.GDP.MKTP.CD,1.242289e+09,1.547389e+09,1.710004e+09,1.539681e+09,1.975702e+09,1.890769e+09,...,5.126439e+10,5.753123e+10,5.723601e+10,5.327430e+10,5.723665e+10,6.423397e+10,6.451504e+10,6.123115e+10,5.356076e+10,5.931948e+10
255,United States,USA,GDP (current US$),NY.GDP.MKTP.CD,5.433000e+11,5.633000e+11,6.051000e+11,6.386000e+11,6.858000e+11,7.437000e+11,...,1.625400e+13,1.684320e+13,1.755070e+13,1.820600e+13,1.869510e+13,1.947730e+13,2.053310e+13,2.138100e+13,2.106050e+13,2.331510e+13
256,Uzbekistan,UZB,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,6.751735e+10,7.318004e+10,8.084538e+10,8.619627e+10,8.613829e+10,6.208132e+10,5.263314e+10,5.990767e+10,5.989431e+10,6.923890e+10
257,St. Vincent and the Grenadines,VCT,GDP (current US$),NY.GDP.MKTP.CD,1.306656e+07,1.399988e+07,1.452488e+07,1.370822e+07,1.475821e+07,1.510821e+07,...,7.300326e+08,7.647813e+08,7.709014e+08,7.865546e+08,8.143023e+08,8.476202e+08,8.843282e+08,9.101497e+08,8.721346e+08,9.041815e+08
258,"Venezuela, RB",VEN,GDP (current US$),NY.GDP.MKTP.CD,7.779091e+09,8.189091e+09,8.946970e+09,9.753333e+09,8.099318e+09,8.427778e+09,...,3.812860e+11,3.710050e+11,4.823590e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,British Virgin Islands,VGB,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,Virgin Islands (U.S.),VIR,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.089000e+09,3.738000e+09,3.565000e+09,3.663000e+09,3.798000e+09,3.794000e+09,3.922000e+09,4.117000e+09,4.204000e+09,NaN
261,Vietnam,VNM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.955910e+11,2.137090e+11,2.334510e+11,2.392580e+11,2.570960e+11,2.813540e+11,3.101060e+11,3.343650e+11,3.466160e+11,3.661380e+11
262,Vanuatu,VUT,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,7.478397e+08,7.583045e+08,7.723157e+08,7.308706e+08,7.808896e+08,8.800621e+08,9.147370e+08,9.365263e+08,8.968799e+08,9.563327e+08
263,World,WLD,GDP (current US$),NY.GDP.MKTP.CD,1.392280e+12,1.448630e+12,1.550550e+12,1.671610e+12,1.830290e+12,1.993910e+12,...,7.550120e+13,7.760720e+13,7.973320e+13,7.518780e+13,7.646150e+13,8.140070e+13,8.645690e+13,8.764530e+13,8.510560e+13,9.651310e+13
264,Samoa,WSM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,7.731575e+08,7.977287e+08,7.966983e+08,8.241600e+08,8.439296e+08,8.848472e+08,8.784351e+08,9.129445e+08,8.689045e+08,8.438424e+08
265,Kosovo,XKX,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,6.163785e+09,6.735731e+09,7.074658e+09,6.295820e+09,6.682833e+09,7.180813e+09,7.878509e+09,7.899879e+09,7.716925e+09,9.412034e+09
266,"Yemen, Rep.",YEM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.540132e+10,4.041523e+10,4.322859e+10,4.244450e+10,3.131783e+10,2.684223e+10,2.160616e+10,NaN,NaN,NaN
267,South Africa,ZAF,GDP (current US$),NY.GDP.MKTP.CD,8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,...,4.344010e+11,4.008860e+11,3.811990e+11,3.467100e+11,3.235860e+11,3.814490e+11,4.041600e+11,3.885320e+11,3.376200e+11,4.190150e+11
268,Zambia,ZMB,GDP (current US$),NY.GDP.MKTP.CD,7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,...,2.550306e+10,2.803724e+10,2.714102e+10,2.125122e+10,2.095841e+10,2.587360e+10,2.631159e+10,2.330867e+10,1.811063e+10,2.214763e+10
269,Zimbabwe,ZWE,GDP (current US$),NY.GDP.MKTP.CD,1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,...,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,1.758489e+10,3.415607e+10,2.183223e+10,2.150970e+10,2.837124e+10

In [420]:

gdpCA = gdpC.iloc[:, [0]]

In [421]:
gdpCA

3         Country Name
0                  NaN
1    Last Updated Date
2                  NaN
3         Country Name
4                Aruba
..                 ...
265             Kosovo
266        Yemen, Rep.
267       South Africa
268             Zambia
269           Zimbabwe

[270 rows x 1 columns]

In [422]:
gdpCB = gdpC.loc[:, '1980.0':'2021.0'] #This is the year range for the energy dataset

In [423]:
gdpCB

3,1980.0,1981.0,1982.0,1983.0,1984.0,1985.0,1986.0,1987.0,1988.0,1989.0,...,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.980000e+03,1.981000e+03,1.982000e+03,1.983000e+03,1.984000e+03,1.985000e+03,1.986000e+03,1.987000e+03,1.988000e+03,1.989000e+03,...,2.012000e+03,2.013000e+03,2.014000e+03,2.015000e+03,2.016000e+03,2.017000e+03,2.018000e+03,2.019000e+03,2.020000e+03,2.021000e+03
4,NaN,NaN,NaN,NaN,NaN,NaN,4.055866e+08,4.877095e+08,5.966480e+08,6.955307e+08,...,2.615084e+09,2.727933e+09,2.791061e+09,2.963128e+09,2.983799e+09,3.092179e+09,3.202235e+09,3.368970e+09,2.610039e+09,3.126019e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.163785e+09,6.735731e+09,7.074658e+09,6.295820e+09,6.682833e+09,7.180813e+09,7.878509e+09,7.899879e+09,7.716925e+09,9.412034e+09
266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.540132e+10,4.041523e+10,4.322859e+10,4.244450e+10,3.131783e+10,2.684223e+10,2.160616e+10,NaN,NaN,NaN
267,8.941189e+10,9.314148e+10,8.590407e+10,9.620411e+10,8.487013e+10,6.445938e+10,7.335478e+10,9.653575e+10,1.039770e+11,1.080560e+11,...,4.344010e+11,4.008860e+11,3.811990e+11,3.467100e+11,3.235860e+11,3.814490e+11,4.041600e+11,3.885320e+11,3.376200e+11,4.190150e+11
268,3.829500e+09,3.872667e+09,3.994778e+09,3.216308e+09,2.739444e+09,2.281258e+09,1.661949e+09,2.269895e+09,3.713614e+09,3.998638e+09,...,2.550306e+10,2.803724e+10,2.714102e+10,2.125122e+10,2.095841e+10,2.587360e+10,2.631159e+10,2.330867e+10,1.811063e+10,2.214763e+10
269,6.678868e+09,8.011374e+09,8.539701e+09,7.764067e+09,6.352126e+09,5.637259e+09,6.217524e+09,6.741215e+09,7.814784e+09,8.286323e+09,...,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,1.758489e+10,3.415607e+10,2.183223e+10,2.150970e+10,2.837124e+10

In [424]:
gdpC = pd.concat([gdpCA,gdpCB], axis=1)

In [425]:
gdpC

3,Country Name,1980.0,1981.0,1982.0,1983.0,1984.0,1985.0,1986.0,1987.0,1988.0,...,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Last Updated Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Country Name,1.980000e+03,1.981000e+03,1.982000e+03,1.983000e+03,1.984000e+03,1.985000e+03,1.986000e+03,1.987000e+03,1.988000e+03,...,2.012000e+03,2.013000e+03,2.014000e+03,2.015000e+03,2.016000e+03,2.017000e+03,2.018000e+03,2.019000e+03,2.020000e+03,2.021000e+03
4,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,4.055866e+08,4.877095e+08,5.966480e+08,...,2.615084e+09,2.727933e+09,2.791061e+09,2.963128e+09,2.983799e+09,3.092179e+09,3.202235e+09,3.368970e+09,2.610039e+09,3.126019e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,Kosovo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.163785e+09,6.735731e+09,7.074658e+09,6.295820e+09,6.682833e+09,7.180813e+09,7.878509e+09,7.899879e+09,7.716925e+09,9.412034e+09
266,"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.540132e+10,4.041523e+10,4.322859e+10,4.244450e+10,3.131783e+10,2.684223e+10,2.160616e+10,NaN,NaN,NaN
267,South Africa,8.941189e+10,9.314148e+10,8.590407e+10,9.620411e+10,8.487013e+10,6.445938e+10,7.335478e+10,9.653575e+10,1.039770e+11,...,4.344010e+11,4.008860e+11,3.811990e+11,3.467100e+11,3.235860e+11,3.814490e+11,4.041600e+11,3.885320e+11,3.376200e+11,4.190150e+11
268,Zambia,3.829500e+09,3.872667e+09,3.994778e+09,3.216308e+09,2.739444e+09,2.281258e+09,1.661949e+09,2.269895e+09,3.713614e+09,...,2.550306e+10,2.803724e+10,2.714102e+10,2.125122e+10,2.095841e+10,2.587360e+10,2.631159e+10,2.330867e+10,1.811063e+10,2.214763e+10
269,Zimbabwe,6.678868e+09,8.011374e+09,8.539701e+09,7.764067e+09,6.352126e+09,5.637259e+09,6.217524e+09,6.741215e+09,7.814784e+09,...,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,1.758489e+10,3.415607e+10,2.183223e+10,2.150970e+10,2.837124e+10

In [426]:
gdpC =gdpC.loc[263]

In [427]:
gdpC #Dataset #2

3
Country Name               World
1980.0          11336600000000.0
1981.0          11727600000000.0
1982.0          11609800000000.0
1983.0          11840100000000.0
1984.0          12271600000000.0
1985.0          12862200000000.0
1986.0          15207800000000.0
1987.0          17310300000000.0
1988.0          19341200000000.0
1989.0          20197500000000.0
1990.0          22783800000000.0
1991.0          23763600000000.0
1992.0          25410300000000.0
1993.0          25826300000000.0
1994.0          27876800000000.0
1995.0          31048500000000.0
1996.0          31741900000000.0
1997.0          31627800000000.0
1998.0          31546600000000.0
1999.0          32745500000000.0
2000.0          33839600000000.0
2001.0          33624000000000.0
2002.0          34918000000000.0
2003.0          39152300000000.0
2004.0          44124000000000.0
2005.0          47784400000000.0
2006.0          51780200000000.0
2007.0          58349500000000.0
2008.0          64120800000000.0
2009.0          60804100000000.0
2010.0          66605800000000.0
2011.0          73857600000000.0
2012.0          75501200000000.0
2013.0          77607200000000.0
2014.0          79733200000000.0
2015.0          75187800000000.0
2016.0          76461500000000.0
2017.0          81400700000000.0
2018.0          86456900000000.0
2019.0          87645300000000.0
2020.0          85105600000000.0
2021.0          96513100000000.0
Name: 263, dtype: object

In [430]:
energyC.to_csv('energyC.csv')
gdpC.to_csv ('gdpC.csv')